#!/bin/sh
# Guest PID1 helper (after cautem-init): optional noVNC stack, then sleep.
set -eu
if [ "${DISPLAY_MODE:-none}" = "novnc" ]; then
  /usr/local/bin/cautem-display-start
fi
if [ "$#" -gt 0 ]; then
  exec "$@"
fi
exec sleep infinity
